**Sensor Temperature Analysis by using NUMPY**

In [ ]:
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])
print(data)

[[22.5 19.  31.2 28.7 25.1]
 [17.3 22.8 30.5 26.4 21.9]
 [33.1 29.6 18.4 24.  27.8]
 [20.2 23.5 31.9 28.1 22.6]]


Imported the numpy packages and short form of name as np.
data create a new variable. It included of np.array and their values.
Display the data values on output window.print(data)


**Task 1 :Print the shape of data. Then compute and print the mean temperature per station (one value per row).**

In [ ]:
# Print shape
print("Shape of data:", data.shape)

# Mean temperature per station (row-wise)
mean_per_station = data.mean(axis=1)
print("Mean temperature per station:", mean_per_station)

Shape of data: (4, 5)
Mean temperature per station: [25.3  23.78 26.58 25.26]


Above coding field given the data values find the shape of data.(Print("Shape of data:", data.shape)
Find the mean values :
New create variable mean_per_station,Output of Mean temperature per station.

**Task 2 Using a boolean mask, extract all temperature readings above 28.0°C and print them as a 1D array.**

In [ ]:
# Boolean mask for values > 28
above_28 = data[data > 28.0]

print("Temperatures above 28°C:", above_28)

Temperatures above 28°C: [31.2 28.7 30.5 33.1 29.6 31.9 28.1]


Find the Boolean Mask value greater than above 28.0.It Output given the 7 values above the 28.[31.2 28.7 30.5 33.1 29.6 31.9 28.1]

**Normalize the entire data array to the range [0, 1] using the formula below and print the result rounded to 2 decimal places:**

In [ ]:
normalized = (data - data.min()) / (data.max() - data.min())

# Round to 2 decimal places
normalized_rounded = np.round(normalized, 2)

print("Normalized Data:")
print(normalized_rounded)

Normalized Data:
[[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]


normalized = (data - data.min()) / (data.max() - data.min())
above formula use normalized value to check the process.
after that get a normalized values are round the 2 decimal places check and print the display of Normalized data and normalized rounded data values.